### PR TITLE
feat: Improvements to get default value

### PR DESCRIPTION
**Pull request by lucasmezencio**
I realised that the `defaultValue` was coming together with the `@default()` notation.

Removed, and moved it into its own method. :)

### CODE REVIEW

**Comment by lucasmezencio** [comment]
@AhmedElywa quick question: any idea when will this be released?

**Comment by AhmedElywa** [comment]
@lucasmezencio I will work on some other updates tomorrow and try to release it.

**Comment by lucasmezencio** [comment]
@AhmedElywa pleeeease? 💜

**Comment by AhmedElywa** [comment]
I am so sorry. I will work on it now

**Comment by AhmedElywa** [comment]
@lucasmezencio done

**Comment by lucasmezencio** [comment]
@AhmedElywa thanks a whole lot!

**Pull request merged**
